import numpy as np

def fill_alpha_fragment_blur(img: np.ndarray, threshold: float, iterations: int, fragment_count: int) -> np.ndarray: ...
def fill_alpha_extend_color(img: np.ndarray, threshold: float, iterations: int) -> np.ndarray: ...
def fill_alpha_nearest_color(img: np.ndarray, threshold: float, min_radius: int, anti_aliasing: bool) -> np.ndarray: ...
