[package]
name = "test-util"
version = "0.0.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
glam.workspace = true
image.workspace = true
image-core.workspace = true

[features]
snap-write = []
